/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { QuestionnaireService } from "../questionnaire.service";
import { QuestionnaireCreateInput } from "./QuestionnaireCreateInput";
import { Questionnaire } from "./Questionnaire";
import { QuestionnaireFindManyArgs } from "./QuestionnaireFindManyArgs";
import { QuestionnaireWhereUniqueInput } from "./QuestionnaireWhereUniqueInput";
import { QuestionnaireUpdateInput } from "./QuestionnaireUpdateInput";
import { SuggestionRequestFindManyArgs } from "../../suggestionRequest/base/SuggestionRequestFindManyArgs";
import { SuggestionRequest } from "../../suggestionRequest/base/SuggestionRequest";
import { SuggestionRequestWhereUniqueInput } from "../../suggestionRequest/base/SuggestionRequestWhereUniqueInput";

export class QuestionnaireControllerBase {
  constructor(protected readonly service: QuestionnaireService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Questionnaire })
  async createQuestionnaire(
    @common.Body() data: QuestionnaireCreateInput
  ): Promise<Questionnaire> {
    return await this.service.createQuestionnaire({
      data: {
        ...data,

        customer: data.customer
          ? {
              connect: data.customer,
            }
          : undefined,
      },
      select: {
        answers: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        questions: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Questionnaire] })
  @ApiNestedQuery(QuestionnaireFindManyArgs)
  async questionnaires(
    @common.Req() request: Request
  ): Promise<Questionnaire[]> {
    const args = plainToClass(QuestionnaireFindManyArgs, request.query);
    return this.service.questionnaires({
      ...args,
      select: {
        answers: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        questions: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Questionnaire })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async questionnaire(
    @common.Param() params: QuestionnaireWhereUniqueInput
  ): Promise<Questionnaire | null> {
    const result = await this.service.questionnaire({
      where: params,
      select: {
        answers: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        questions: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Questionnaire })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateQuestionnaire(
    @common.Param() params: QuestionnaireWhereUniqueInput,
    @common.Body() data: QuestionnaireUpdateInput
  ): Promise<Questionnaire | null> {
    try {
      return await this.service.updateQuestionnaire({
        where: params,
        data: {
          ...data,

          customer: data.customer
            ? {
                connect: data.customer,
              }
            : undefined,
        },
        select: {
          answers: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          id: true,
          questions: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Questionnaire })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteQuestionnaire(
    @common.Param() params: QuestionnaireWhereUniqueInput
  ): Promise<Questionnaire | null> {
    try {
      return await this.service.deleteQuestionnaire({
        where: params,
        select: {
          answers: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          id: true,
          questions: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/suggestionRequests")
  @ApiNestedQuery(SuggestionRequestFindManyArgs)
  async findSuggestionRequests(
    @common.Req() request: Request,
    @common.Param() params: QuestionnaireWhereUniqueInput
  ): Promise<SuggestionRequest[]> {
    const query = plainToClass(SuggestionRequestFindManyArgs, request.query);
    const results = await this.service.findSuggestionRequests(params.id, {
      ...query,
      select: {
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,

        questionnaire: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/suggestionRequests")
  async connectSuggestionRequests(
    @common.Param() params: QuestionnaireWhereUniqueInput,
    @common.Body() body: SuggestionRequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      suggestionRequests: {
        connect: body,
      },
    };
    await this.service.updateQuestionnaire({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/suggestionRequests")
  async updateSuggestionRequests(
    @common.Param() params: QuestionnaireWhereUniqueInput,
    @common.Body() body: SuggestionRequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      suggestionRequests: {
        set: body,
      },
    };
    await this.service.updateQuestionnaire({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/suggestionRequests")
  async disconnectSuggestionRequests(
    @common.Param() params: QuestionnaireWhereUniqueInput,
    @common.Body() body: SuggestionRequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      suggestionRequests: {
        disconnect: body,
      },
    };
    await this.service.updateQuestionnaire({
      where: params,
      data,
      select: { id: true },
    });
  }
}
